version: '3'

services:
  postgresql:
    image: postgres
    container_name: url_shortener
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DATABASE=url_shortener
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-url-shortener
    ports:
      - '6379-6379'